services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    # ports:
    #   - "3001:3001"  # This maps the container port "3001" to the host port "3001"
    volumes:
      - /opt/uptime-kuma:/app/data  # Configuring persistent storage
      - /var/run/docker.sock:/var/run/docker.sock # For monitoring Docker containers
    environment:
      - TZ=Europe/Bratislava
      - UMASK=0022  # Set your file permissions manually
    networks:
      proxy:
        ipv4_address: 10.88.255.15
        ipv6_address: fd00:dead:beef:4:ffff::15
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true