name: pgadmin-hub

services:
  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin-hub
    restart: unless-stopped
    # ports:
    #    - "127.0.0.1:8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "True"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      db-net:
        ipv4_address: 10.88.254.254
        ipv6_address: fd00:dead:beef:4:fffe::254
      proxy:
        ipv4_address: 10.88.255.11
        ipv6_address: fd00:dead:beef:4:ffff::11

volumes:
  pgadmin-data:

networks:
  db-net:
    name: proxy
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.88.254.0/24
        - subnet: fd00:dead:beef:4:fffe::/80
  proxy:
    external: true
