services:
  postgresql:
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
    - database:/var/lib/postgresql/data
    networks:
      authentik:
        ipv4_address: 10.88.1.18
        ipv6_address: fd00:dead:beef:4:2::2
  server:
    command: server
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.2.2}
    ports:
    - ${COMPOSE_PORT_HTTP:-9000}:9000
    - ${COMPOSE_PORT_HTTPS:-8443}:9443
    restart: unless-stopped
    shm_size: 512mb
    volumes:
    - /opt/authentik/data:/data
    - /opt/authentik/custom-templates:/templates
    networks:
      authentik:
        ipv4_address: 10.88.1.19
        ipv6_address: fd00:dead:beef:4:2::3
      proxy:
        ipv4_address: 10.88.255.4
        ipv6_address: fd00:dead:beef:4:ffff::4
  worker:
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.2.2}
    restart: unless-stopped
    shm_size: 512mb
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/authentik/data:/data
    - /opt/authentik/certs:/certs
    - /opt/authentik/custom-templates:/templates
    networks:
      authentik:
        ipv4_address: 10.88.1.20
        ipv6_address: fd00:dead:beef:4:2::4
volumes:
  database:
    driver: local
networks:
  authentik:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.88.1.16/29
        - subnet: fd00:dead:beef:4:2::/80
  proxy:
    external: true